### ISSUE TITLE
RA8875 and Adafruit feather cortex M0

### ISSUE THREAD

**Issue by gsoudee** [sumotoy/RA8875#108]
Hello

I try to make working the R8875 library on a adafruit feather cortexM0.

It's not working? any idea ? is it aproblem with the SAMD21 declaration ?

Thanks for your help

Regards

Guillaume

**Comment by sumotoy** [comment]
I don't have any cortex M0 so I have not idea how to deal with high speed SPI, interrupts and so on.
For this reason currently the library is not compatible.
