### ISSUE TITLE
Arduino Zero / SAMD21 support

### ISSUE THREAD

**Issue by Spomky** [sumotoy/RA8875#137]
Hi,

Is there any plan for the Arduino Zero / SAMD21 support?
I am trying to get it work on a [Sparkfun SAMD21 Mini Breakout Board](https://learn.sparkfun.com/tutorials/samd21-minidev-breakout-hookup-guide/samd21-overview) but unfortunately [it looks like it won’t work](https://github.com/sumotoy/RA8875/blob/0.70b11/_settings/RA8875_CPU_commons.h#L127-L136).

**Comment by Jim-bee** [comment]
Yes, it would be nice to include the Adafruit Feather M0 and M4.

**Comment by AtomSoftTech** [comment]
Would love this as well

**Comment by Spomky** [comment]
Closing as this library looks to be abandonned (no commit for more than 3 years)
