### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by DrewJaworskiRIS** [sumotoy/RA8875#14]
Have you managed to get sleeping to work correctly with the RA8875? I figure my problem is with clock speeds somehow, but I am not sure. I tried implementing what is shown in the RA8875 datasheet page 66, but my current draw only drops down to 199mA, which is the same as what I get when I just turn off the backlight. With my ER-TFTM070-5, I am seeing a current draw of 470mA from a 3.3V supply during normal use, which is close to what the datasheet indicates, but the sleep current draw should be significantly lower!

**Comment by DrewJaworskiRIS** [comment]
Have you made any progress on this? I haven't had time to figure out how to make it work; does it have something to do with the clock speed change that it needs?

**Comment by sumotoy** [comment]
It's quite complicated since I'm driving it serially and if you look at datasheet you will see that needs special procedure to get up from sleep, it needs a lot of changes in code but I'm getting it quickly.

**Comment by sumotoy** [comment]
Ok, the sleep it's coming for the 0.70 (we almost there, actually 0.69). Believe me, it was quite complicated.
Going into sleep mode it's easy, get back it's another story! Have to speed down SPI and many other things, wait until the display get up (this was the tricky part, sometime it wait for forever), re-initialize PWM for display, etc, etc.

**Comment by sumotoy** [comment]
**6-1-2-3 SPI Sleep / Wake Up**
(see datasheet, looks easy but many other stuff it's connected to that!)
