### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by taranathicus** [sumotoy/RA8875#16]
I am using this with the adafruit ra8875 board and I cannot get it to display properly.  Using a setup with the adafruit library it works perfectly,  When I switch to your library(for the added functionality)  The screen will flash like its going to display then goes white.  I found that if jiggle the loose zif connector the display shows up almost like it needs a pin(s) disconnected to work.  I am using the arduino mega and have tried with 1.5.8 and 1.0.6.  I feel like I'm missing a setting or something simple, sorry for the bother and thank you for the response.

edit: Fixed I wasn't initializing as  tft.begin(Adafruit_480x272);   which I would have known had I read the documentation properly.  I am only not deleting completely in case someone else has the same issue.

**Comment by sumotoy** [comment]
thanks!
