### ISSUE TITLE
#define USE_EXTERNALTOUCH

### ISSUE THREAD

**Issue by The-Experimentalist** [sumotoy/RA8875#20]
If this is uncommented you get a compile error. The following is needed in RA8875.cpp to fix:

Line 256-261

	#if !defined(USE_EXTERNALTOUCH)
		/*	Touch Panel Control Register 0     [0x70]
		7: 0(disable, 1:(enable)
		6,5,4:TP Sample Time Adjusting (000...111)
		3:Touch Panel Wakeup Enable 0(disable),1(enable)
		2,1,0:ADC Clock Setting (000...111) set fixed to 010: (System CLK) / 4, 10Mhz Max! */
		_TPCR0Reg = RA8875_TPCR0_WAIT_4096CLK | RA8875_TPCR0_WAKEDISABLE | RA8875_TPCR0_ADCCLK_DIV4;
	#endif

**Comment by sumotoy** [comment]
Thanks, fixed for the incoming 0.69b2 (with 8 bit support)
