### ISSUE TITLE
oldpapa

### ISSUE THREAD

**Issue by Oldpapa** [sumotoy/RA8875#35]
Using adafruit with teensy 3.1
Black screen using tft.begin(Adafruit_800x480);
If tft.begin(RA8875_800x480); I get a white screen.  

Either case, nothing displays.

**Comment by sumotoy** [comment]
Did you have any other stuff connected to SPI?

**Comment by sumotoy** [comment]
I think I find the issue, fixing now...wait

**Comment by Oldpapa** [comment]
Nothing, only display

**Comment by sumotoy** [comment]
looks like the release online missed the gpio command where adafruit connected the display backlight. In a min I give a piece of code to add and you should be ready to go

**Comment by Oldpapa** [comment]
ok, be here

**Comment by sumotoy** [comment]
In the RA8875::initialize() function , after displayOn(true); add...

	if (_size == Adafruit_480x272 || _size == Adafruit_800x480) GPIOX(true);//only for adafruit stuff 
	PWMsetup(1,true, RA8875_PWM_CLK_DIV1024);//setup PWM ch 1 for backlight
	PWMout(1,255);//turn on PWM1

**Comment by sumotoy** [comment]
tft.begin(Adafruit_800x480);

**Comment by Oldpapa** [comment]
It Works..!!

**Comment by sumotoy** [comment]
so there's an issue on backlight, I have to fix this...

**Comment by Oldpapa** [comment]
Ok, well, I was not crazy after all
I can now use your library to do more..

Great, TY Sir!

**Comment by sumotoy** [comment]
This library it's much more fast than adafruit and also doesn't have a lot of errors never fixed on adafruit one, the list is too long, this is wy I waste my time to develop it,

**Comment by Oldpapa** [comment]
You are not wasting time..  Not at all..

**Comment by sumotoy** [comment]
Can you please go tho Teensy forum and says this is solved? Thanks for your time!

**Comment by Oldpapa** [comment]
Yes I will..
