### ISSUE TITLE
The infamous square qr-code like that appear sometime on top-left...

### ISSUE THREAD

**Issue by sumotoy** [sumotoy/RA8875#57]
In some situation (almost related to Layers) sometime appears on top-left a qr-code like square that doesn't go away.
This not happen always!
Since it's not easily replicable I have some trouble to understand what cause this but I'm pretty sure can be fixed really soon, I'm pretty sure it's caused by an RA8875 hardware bug related to some register timing during startup initialization.
I have noticed that appear more frequently if you using the reset pin and this point me to an initialization tweak.

**Comment by The-Experimentalist** [comment]
I have rewritten this comment as I got the issues mixed up. This particular issue, the QR code, has gone away and not returned for me since I changed the SdFat library to use the standard Arduino SPI library instead of the fast custom SPI implementation in the SdFat library:

#define SD_SPI_CONFIGURATION 1

**Comment by sumotoy** [comment]
Thanks, but I've noticed it return from time to time. I've finally detect where is the problem and get fixed in some days!

**Comment by sumotoy** [comment]
Ok, find the cause, it's a power supply problem! The RA8875 expect exact 3V3 volts, going under that value create problems with his internal memory.
Since the Eastrising display (some) has an internal LDO regulator from 5V to 3V3 that has a drop, giving less than 4.8V don't permit LDO to compensate the drop.
The solution it's simple, don't supply less that 5 volt (or 3V3).
I have tested several times giving less than 4V8 and always replicate the problem.
