### ISSUE TITLE
Font centering using internal font is no longer centered

### ISSUE THREAD

**Issue by The-Experimentalist** [sumotoy/RA8875#60]
When I compile with 0.70 fonts are correctly centered, with 0.70b5 they tend to the bottom right hand corner. I will test more later and report back. 

This is using internal fonts.

**Comment by sumotoy** [comment]
ah, ok. It's an easy fix. I'll check and fix later

**Comment by sumotoy** [comment]
Are you sure about this issue?
look at the following code...

```
  tft.setFontScale(3);
  //tft.setCursor(CENTER, CENTER);
  tft.setCursor(tft.width()/2, tft.height()/2,true);
  tft.print("AA AA");
  tft.drawLine(0, 0, tft.width(), tft.height(), RA8875_RED);
  tft.drawLine(0, tft.height(), tft.width(), 0, RA8875_RED);
  tft.drawFastHLine(0, tft.height() / 2, tft.width(), RA8875_RED);
  tft.drawFastVLine(tft.width() / 2, 0, tft.height(), RA8875_RED);
```

Looks perfectly centered, at any scale and using CENTER or autocenter flag!!!!

**Comment by The-Experimentalist** [comment]
Sorry for slow reply, been away. Not had chance to test this yet. All I know is when I compile with the later code all my button legends went off centre. Will probably not get any time to work on this again for a couple of weeks

**Comment by sumotoy** [comment]
no prob, I'll close it, eventually you can still open again issue if you find something else I've missed.
