### ISSUE TITLE
ER3301-1 External font support

### ISSUE THREAD

**Issue by WerkAG** [sumotoy/RA8875#72]
Could you please add support for the external font ER3301-1, or give me some pointers on how to do it?
This external font is important for those who need Latin characters.
Thank you.

**Comment by sumotoy** [comment]
Ok, I will order one and see, unfortunatly every chip it's different and datasheet doesn't help as it should.

**Comment by WerkAG** [comment]
Thank you :-)
I have spent last two nights trying to make some changes in your library to use the font chip, but without any success. I'm a very poor programmer too!
No rush, until you add support for it, I will continue trying, this way I also learn something.

**Comment by WerkAG** [comment]
Hi,

Seems that the ER3301-1 font ROM, is equivalent to Genicomp GT30L16U2W.
It works if I define GT30L16U2W as external font chip.

Nice job, 0.70b11 is working good. 800x480 resistive touch, ATmega 1284p

**Comment by sumotoy** [comment]
thanks, in upcoming b6 you can assign as ER3301_1
