### ISSUE TITLE
0.70b12

### ISSUE THREAD

**Issue by sumotoy** [sumotoy/RA8875#78]
New beta has support for 'icon' files, better support for STM32, ESP and some code speedup.
I will try to complete the keypad as well.

**Comment by morpheous87** [comment]
When the 0.70b12 will be commit in the source?

**Comment by sumotoy** [comment]
b12 has massive changes and STM32 support it's a mess, have to revrote low level SPI routines separately, I'm actually adding ESP8266 support.
It will take time, I have to use my spare time unfortunatly.
Btw I'm planning to upload soon a version with small updates and icon support before b12

**Comment by morpheous87** [comment]
I'm really interested in the  icon support, that's why I asked.

Thanks
