### ISSUE TITLE
STM32F407 library for project.

### ISSUE THREAD

**Issue by imoldovavan** [sumotoy/RA8875#89]
Hello,
I am looking for a library for the 7in TFT but it needs to work with the STM32F407. How close is this library to working with this chip? This is for an open source sdr radio, details of the software and hardware: https://github.com/df8oe/mchf-github; http://www.m0nka.co.uk/. 
I used an arduino with this library and the 7inTFT display and I really like it. Good job.
Thank you,
Ion

**Comment by sumotoy** [comment]
Some other asked for this but I don't have any ST so I cannot respond.
I've taked a look time ago inside a SPI library from ST and I was not impressed at all, commands are basic and can't find a way to modulate SPI speed (this library needs this), a Japanese guy ported my other ILI9163C for ST by using high speed DMA SPI, maybe take a look to his work as starting point.
Actually I don't own ST stuff so I cannot help.
